# Generated by Django 4.2.5 on 2023-10-01 12:34

from django.db import migrations


def migrate_redirection_status(apps, schema_editor):
    Redirection = apps.get_model("redirections", "Redirection")

    for redirection in Redirection.objects.all():
        redirection.redirection_type = int(redirection.redirection_code)
        redirection.save()


class Migration(migrations.Migration):
    dependencies = [
        ("redirections", "0003_redirection_redirection_type"),
    ]

    operations = [migrations.RunPython(migrate_redirection_status)]
