# Generated by Django 4.2.5 on 2023-10-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirections', '0004_auto_20231001_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redirection',
            name='redirection_code',
        ),
    ]
