# Generated by Django 4.2.5 on 2023-10-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirections', '0005_remove_redirection_redirection_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirection',
            name='redirection_type',
            field=models.IntegerField(choices=[(301, 'Permanent'), (302, 'Temporary')], default=302),
        ),
    ]
