# Generated by Django 4.2.5 on 2023-10-01 12:57

from django.db import migrations


def migrate_status(apps, schema_editor):
    Redirection = apps.get_model("redirections", "Redirection")

    for redirection in Redirection.objects.all():
        redirection.status_new = redirection.status[:2]
        redirection.save()


class Migration(migrations.Migration):
    dependencies = [
        ("redirections", "0007_redirection_status_new"),
    ]

    operations = [migrations.RunPython(migrate_status)]
