# Generated by Django 4.2.5 on 2023-10-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redirections", "0008_auto_20231001_1457"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="redirection",
            name="status",
        ),
        migrations.RenameField(
            model_name="redirection",
            old_name="status_new",
            new_name="status",
        ),
    ]
