# Generated by Django 4.2.5 on 2023-10-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirections', '0009_remove_redirection_status_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirection',
            name='staged_redirect',
            field=models.BooleanField(default=False),
        ),
    ]
